# Generated by Django 4.1.7 on 2023-03-26 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_png', models.FileField(blank=True, null=True, upload_to='scan_png/')),
                ('scan_pdf', models.FileField(blank=True, null=True, upload_to='scan_pdf/')),
                ('upload_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.uploadfiles')),
            ],
        ),
    ]
