# Generated by Django 4.1.7 on 2023-03-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_resultfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='type',
            field=models.CharField(choices=[('Документ', 'Документ'), ('МК', 'МК'), ('Виза', 'Виза')], default='123', max_length=255, verbose_name='Тип документа'),
            preserve_default=False,
        ),
    ]
